context:
  version: 1.39.12

package:
  name: omnisharp-roslyn
  version: ${{ version }}

source:
  git: https://github.com/OmniSharp/omnisharp-roslyn
  tag: v${{ version }}

build:
  number: 1
  noarch: generic

requirements:
  build:
    - sed
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - OmniSharp --help

about:
  license: MIT
  license_file:
    - license.md
    - license-files/
  summary: OmniSharp server (HTTP, STDIO) based on Roslyn workspaces
  homepage: https://github.com/OmniSharp/omnisharp-roslyn

extra:
  recipe-maintainers:
    - danielnachun
